### ISSUE TITLE
Método update

### ISSUE THREAD

**Issue by ghost** [Rocketseat/bootcamp-gostack-desafio-01#1]
Olá, ao terminar o desafio fui conferir a resposta para ver se poderia melhorar o meu código e também aprender novas formas. 

Porém observei um caso que acredito ser necessário alterar. 

No método **update** é passado seguinte trecho de código: 

```
const project = projects.find(p => p.id === id);

project.title = title;

return res.json(project);
```

O que observei é que isso altera apenas o projeto instanciado na **const project**, e não no projeto que já está no **array**.

Não deveria buscar o index com o endereço no array, e substituir esse elemento no array? 

Fiz algo como: 

```
const project = projects.find(p => p.id == id);
project.title = title;

const index = projects.findIndex(p => p.id == id);
projects[index] = project;

return res.json(projects);

```
Acredito que talvez há formas de escrever esse meu código melhor.. mas ainda estou aprendendo.

**Comment by kaiopessoni** [comment]
Pois é, também percebi isso, no meu código eu atualizei o array projects pelo index.

**Comment by anjoshigor** [comment]
Olá,

Existem duas coisas a serem esclarecidas para te ajudar nessa dúvida:

1.  Não é uma boa prática retornar a lista completa em métodos `PUT`

Imagine que a sua lista de projetos cresceu e tem 1 milhão de elementos. Quando um usuário alterar apenas um elemento dessa lista, ou seja, apenas um projeto que ele tá trabalhando, faz sentido ele receber toda a lista como resposta? Pois bem, se o usuário desejar visualizar a lista inteira depois de sua modificação, basta ele utilizar o `GET`.

2. A variável `project` é uma referência.

Quando você usa a função find e obtém o projeto encontrado, você possui a referência para ele "em mãos" e quando o modifica, também modifica o elemento da lista. Para fazer um teste, pode rodar esse pequeno trecho de código e entender o seu funcionamento.
```js
const projects = [
  { id: 1, title: "p1" }, 
  { id: 1, title: "p2" }
];

console.log(projects);

const project = projects.find(p => p.id === 1);

project.title = "projeto1";

console.log(projects);

//Saída esperada
//1.
// [
//  { id: 1, title: "p1" }, 
//  { id: 1, title: "p2" }
//]
//
// 2.
//[
//  { id: 1, title: "projeto1" }, 
//  { id: 1, title: "p2" }
//]
//
```

Se você deseja obter realmente um novo objeto com as mesmas propriedades do projeto encontrado, deixo aqui duas abordagens diferentes:

```js
const projectObjectAssign = Object.assign({}, projects.find(p => p.id === 1));
const projectDeconstruction = {... projects.find(p => p.id === 1)};
```

Espero ter ajudado.

**Comment by blindibrasil** [comment]
Gostaria de mais informações sobre o método utilizado para localizar o item pelo id para fazer o update pois não entendi direito onde foi obtido este "p".
`projects.find(p => p.id === id);`

**Comment by JRGGRoberto** [comment]
Olá, minha sugestão mais um método PUT para alterar o nome da tarefa passando somente o id
http://localhost:4000/projects/SDU/tasks/0
JSON
```
{
	"title": "Santos Dumond"
}
```
Método
```
server.put('/projects/:id/tasks/:index', checkProjectExists, (req, res) => {
  const { id, index } = req.params;
  const { title } = req.body;
  const project = projects.find(p => p.id == id);
  if(project.tasks.length >= 0 &  index < project.tasks.length){
    project.tasks[index] = title;
    return res.json(project);
  }
  return res.status(404).json({error: 'Task not found'});
});

```

**Comment by jpedroschmitz** [comment]
Fala galera, adorei ver vocês trocando ideias sobre as melhores formas de abordar a rota de `put`. Se alguém tiver alguma solução e quiser que a mesma seja colocada no repositório saibam que toda PR é muito bem vinda 💜 Vou fechar essa issue, mas em qualquer caso eu abro novamente 👊
