### ISSUE TITLE
Middleware para contar o numero de requisições

### ISSUE THREAD

**Issue by maykonsousa** [Rocketseat/bootcamp-gostack-desafio-01#12]
Eu nao sei se fiz certo, mas acho que se tier certa, a minha ficou mais simples que a descrita na solução

server.use((req,res,next)=>{
console.count('Count Request');
next();
})

**Comment by samuelpqd** [comment]
> Eu nao sei se fiz certo, mas acho que se tier certa, a minha ficou mais simples que a descrita na solução
> 
> server.use((req,res,next)=>{
> console.count('Count Request');
> next();
> })

Sim, funciona. Testei sua forma de contar as requisições e funciona certinho também.
