### ISSUE TITLE
Console count

### ISSUE THREAD

**Issue by dcaueb78** [Rocketseat/bootcamp-gostack-desafio-01#5]
No meu exercício utilizei uma forma que acredito ser melhor para fazer o count de requests: `console.count("Number of Requests")` no lugar da criação e incrementação de variável.

**Comment by lcelso** [comment]
Eu também utilizei o count e adicionei mais logs: 
<img width="486" alt="Logs" src="https://user-images.githubusercontent.com/677288/66891703-3694ee00-efc0-11e9-86d1-b8e3fc1c7511.png">

```
function applicationsLogs(req, res, next) {
  const { url, method } = req;
  const end = res.end;

  const data = {
    index: {
      method,
      url
    }
  };

  res.end = function(chunk, encoding) {
    data.index.statusCode = res.statusCode;

    console.time("request");
    console.group("Total Requests");
    console.count("Total number of requests made is");
    console.groupEnd();
    console.table(data);
    console.timeEnd("request");

    res.end = end;
    res.end(chunk, encoding);
  };

  return next();
}
```

**Comment by jpedroschmitz** [comment]
Fala @dcaueb78, se quiser abrir uma PR para melhorar o código ela será muito bem vindo 💜

**Comment by jpedroschmitz** [comment]
Vou fechar essa issue visto que foi feito o merge da PR do @dcaueb78 em #7 💜
